/**
 * A drawn plan the sheet's tests read: rooms placed by hand on two storeys, with the doors drawn on
 * them and the edges those doors draw, kept as test data only.
 */

import { sheetOf, type Door, type Poly, type Room, type Settings, type Sheet } from './model'
import { repair } from './kinds'

type SavedRoom = Omit<Room, 'cat' | 'angle' | 'pieces'> & {
  cat: string
  angle?: number
  pieces?: Poly[] | null
}

const EMBEDDED_ROOMS: SavedRoom[] = [
  {
    angle: 0,
    cat: 'shared',
    h: 2,
    id: 'r0',
    kind: 'entry-foyer',
    lost: {
      h: 1.25,
      w: 0,
    },
    name: 'Entry',
    pieces: null,
    placed: true,
    placedAt: 173,
    target: 8,
    w: 5.61,
    x: 11.39,
    y: 7,
  },
  {
    angle: 0,
    cat: 'circulation',
    h: 3.37,
    id: 'r1',
    kind: 'stair',
    lost: {
      h: 0,
      w: 1.99,
    },
    name: 'Stair',
    pieces: null,
    placed: true,
    placedAt: 115,
    target: 15,
    w: 6.25,
    x: 1.5,
    y: 9,
  },
  {
    angle: 25,
    cat: 'reception',
    h: 7.16,
    id: 'r2',
    kind: 'diwaniya',
    locked: false,
    lost: {
      h: 0.64,
      w: 4.31,
    },
    name: 'Diwaniya',
    pieces: null,
    placed: true,
    placedAt: 141,
    target: 60,
    w: 5.38,
    x: 11.856468,
    y: 15.039586,
  },
  {
    angle: 25,
    cat: 'service',
    h: 3.57,
    id: 'r3',
    kind: 'diwaniya-wc',
    lost: {
      h: 0,
      w: 0.49,
    },
    name: 'Diwaniya WC',
    pieces: null,
    placed: true,
    placedAt: 5,
    target: 5,
    w: 2.12,
    x: 10.84915,
    y: 13.622297,
  },
  {
    angle: 0,
    cat: 'shared',
    h: 9,
    id: 'r5',
    kind: 'family-living',
    lost: {
      h: 0,
      w: 1.5,
    },
    name: 'Family Living',
    pieces: null,
    placed: true,
    placedAt: 67,
    target: 45,
    w: 7.75,
    x: 0,
    y: 0,
  },
  {
    angle: 0,
    cat: 'shared',
    h: 5.5,
    id: 'r6',
    kind: 'formal-living',
    lost: {
      h: 0.19,
      w: 1.5,
    },
    name: 'Formal Living',
    pieces: null,
    placed: true,
    placedAt: 77,
    target: 35,
    w: 7.11,
    x: 11.39,
    y: 1.5,
  },
  {
    angle: 0,
    cat: 'shared',
    h: 6.741356,
    id: 'r7',
    kind: 'dining-room',
    lost: {
      h: 0.316694,
      w: 0.116903,
    },
    name: 'Dining Room',
    pieces: [
      [
        [0, 3.370084],
        [0, 0],
        [8.759824, 0],
      ],
      [
        [0, 3.370084],
        [8.759824, 0],
        [8.759824, 3.366567],
      ],
      [
        [8.759824, 3.366567],
        [7.104909, 6.741356],
        [0, 3.370084],
      ],
    ],
    placed: true,
    placedAt: 101,
    target: 24,
    w: 8.759824,
    x: 9.740176,
    y: 9,
  },
  {
    angle: 0,
    cat: 'shared',
    h: 3.43,
    id: 'r8',
    kind: 'kitchen',
    labelAt: [4.756795, 2.280974],
    lost: {
      h: 0.23,
      w: 2,
    },
    name: 'Kitchen',
    pieces: [
      [
        [3, 1.48],
        [0, 1.48],
        [0, 0],
      ],
      [
        [3, 1.48],
        [0, 0],
        [6.25, 0],
      ],
      [
        [3, 3.43],
        [3, 1.48],
        [6.25, 0],
      ],
      [
        [6.25, 0],
        [6.25, 3.43],
        [3, 3.43],
      ],
    ],
    placed: true,
    placedAt: 1,
    target: 21,
    w: 6.25,
    x: 1.5,
    y: 16.37,
  },
  {
    angle: 0,
    cat: 'service',
    h: 3.5,
    id: 'r10',
    kind: 'guest-wc',
    lost: {
      h: 0,
      w: 0,
    },
    name: 'Guest WC',
    pieces: null,
    placed: true,
    placedAt: 38,
    target: 3,
    w: 3.64,
    x: 7.75,
    y: 3.5,
  },
  {
    angle: 0,
    cat: 'service',
    h: 4,
    id: 'r11',
    kind: 'maid-room',
    lost: {
      h: 0.14,
      w: 1.45,
    },
    name: 'Maid Room',
    pieces: null,
    placed: true,
    placedAt: 7,
    target: 12,
    w: 3.1,
    x: 0,
    y: 12.37,
  },
  {
    angle: 0,
    cat: 'service',
    h: 2.5,
    id: 'r12',
    kind: 'maid-bathroom',
    lost: {
      h: 0.05,
      w: 2.55,
    },
    name: 'Maid Bath',
    pieces: null,
    placed: true,
    placedAt: 8,
    target: 4.5,
    w: 2.25,
    x: 3.1,
    y: 12.37,
  },
  {
    angle: 0,
    cat: 'service',
    h: 3.2,
    id: 'r13',
    kind: 'driver-room',
    labelAt: [4.56679, 1.076883],
    lost: {
      h: 0,
      w: 0,
    },
    name: 'Driver Room',
    pieces: [
      [
        [3, 1.8],
        [3, 0],
        [6.25, 0],
      ],
      [
        [3, 1.8],
        [6.25, 0],
        [6.25, 3.2],
      ],
      [
        [0, 1.8],
        [3, 1.8],
        [6.25, 3.2],
      ],
      [
        [6.25, 3.2],
        [0, 3.2],
        [0, 1.8],
      ],
    ],
    placed: true,
    placedAt: 196,
    target: 12,
    w: 6.25,
    x: 1.5,
    y: 19.8,
  },
  {
    angle: 0,
    cat: 'service',
    h: 1.8,
    id: 'r14',
    kind: 'driver-bathroom',
    lost: {
      h: 0,
      w: 0.35,
    },
    name: 'Driver Bath',
    pieces: null,
    placed: true,
    placedAt: 210,
    target: 4.5,
    w: 3,
    x: 1.5,
    y: 19.8,
  },
  {
    angle: 0,
    cat: 'service',
    h: 1.95,
    id: 'r15',
    kind: 'storage',
    lost: {
      h: 0.05,
      w: 0,
    },
    name: 'Store',
    pieces: null,
    placed: true,
    placedAt: 211,
    target: 6,
    w: 3,
    x: 1.5,
    y: 17.85,
  },
  {
    angle: 0,
    cat: 'circulation',
    h: 9.577081,
    id: 'r16',
    kind: 'hallway',
    labelAt: [1.104204, 3.774213],
    lost: {
      h: 3.222919,
      w: 0.443109,
    },
    name: 'Ground Hallway',
    pieces: [
      [
        [2, 5.419221],
        [3.964435, 6.337757],
        [2.453914, 9.577081],
      ],
      [
        [2, 5.419221],
        [2.453914, 9.577081],
        [0, 9.577081],
      ],
      [
        [2, 2],
        [2, 5.419221],
        [0, 9.577081],
      ],
      [
        [2, 2],
        [0, 9.577081],
        [0, 0],
      ],
      [
        [2, 2],
        [0, 0],
        [3.649824, 0],
      ],
      [
        [3.649824, 0],
        [3.649824, 2],
        [2, 2],
      ],
    ],
    placed: true,
    placedAt: 1,
    target: 24,
    w: 3.964435,
    x: 7.740176,
    y: 7,
  },
  {
    angle: 0,
    cat: 'service',
    h: 2.5,
    id: 'nmu3xhurkamdb',
    kind: 'laundry',
    lost: {
      h: 0,
      w: 0.6,
    },
    name: 'laundry',
    pieces: null,
    placed: true,
    placedAt: 10,
    target: 6,
    w: 2.4,
    x: 5.35,
    y: 12.37,
  },
  {
    angle: 0,
    cat: 'circulation',
    h: 1.5,
    id: 'nmu3y9058w92y',
    kind: 'hallway',
    lost: {
      h: 0,
      w: 0.15,
    },
    name: 'service hallway',
    pieces: null,
    placed: true,
    placedAt: 9,
    target: 6,
    w: 4.65,
    x: 3.1,
    y: 14.87,
  },
  {
    angle: 0,
    cat: 'private',
    h: 3.29,
    id: 'nmu436pzls0vk',
    kind: 'bedroom',
    name: 'Bedroom',
    pieces: null,
    placed: false,
    target: 14,
    w: 4.25,
    x: 0,
    y: 0,
  },
]

/** The doors of the plan, by the room that holds each: every one names the edge it draws. */
const DOORS: Record<string, Door[]> = {
  r0: [
    {
      id: 'dmu3ypmqrqt7j',
      edge: 'e-r0-r16',
      to: 'r16',
      type: 'opening',
      w: 1.7,
      flip: false,
      hinge: false,
      along: 0.5,
    },
    {
      id: 'dmu41ksjdtice',
      edge: 'e-EXTERIOR-r0',
      to: 'EXTERIOR',
      type: 'street2',
      w: 1.7,
      flip: false,
      hinge: false,
      at: [5.61, 1],
    },
    {
      id: 'dmu41p7feb2qv',
      edge: 'e-r0-r6',
      to: 'r6',
      type: 'opening',
      w: 3,
      flip: false,
      hinge: false,
      along: 0.5,
    },
  ],
  r1: [
    {
      id: 'dmu42k3d6v62v',
      edge: 'e-r1-r16',
      to: 'r16',
      type: 'open',
      w: 3.27,
      flip: false,
      hinge: false,
      along: 0.5,
    },
  ],
  r2: [
    {
      id: 'dmu41nkhpgn2u',
      edge: 'e-r2-r3',
      to: 'r3',
      type: 'opening',
      w: 1.2,
      flip: false,
      hinge: false,
      along: 0.789813,
    },
    {
      id: 'dmu41uk3gzug2',
      edge: 'e-EXTERIOR-r2',
      to: 'EXTERIOR',
      type: 'street',
      w: 1.2,
      flip: false,
      hinge: false,
      at: [0, 6.41],
    },
    {
      id: 'dmu41q18ldt40',
      edge: 'e-r2-r7',
      to: 'r7',
      type: 'sliding',
      w: 2.5,
      flip: false,
      hinge: false,
      along: 0.463892,
    },
  ],
  r5: [
    {
      id: 'dmu41l0s9u07g',
      edge: 'e-r16-r5',
      to: 'r16',
      type: 'opening',
      w: 1.7,
      flip: false,
      hinge: false,
      along: 0.5,
    },
  ],
  r8: [
    {
      id: 'dmu41mdvxyou6',
      edge: 'e-nmu3y9058w92y-r8',
      to: 'nmu3y9058w92y',
      type: 'door',
      w: 0.9,
      flip: false,
      hinge: true,
      along: 0.870968,
    },
    {
      id: 'dmu41mkp6ha7x',
      edge: 'e-EXTERIOR-r8',
      to: 'EXTERIOR',
      type: 'door',
      w: 0.9,
      flip: false,
      hinge: false,
      at: [0, 0.74],
    },
  ],
  r10: [
    {
      id: 'dmu3yq1lt207l',
      edge: 'e-r10-r16',
      to: 'r16',
      type: 'door',
      w: 0.9,
      flip: false,
      hinge: true,
      along: 0.164835,
    },
  ],
  r11: [
    {
      id: 'dmu41ogbkbr3g',
      edge: 'e-nmu3y9058w92y-r11',
      to: 'nmu3y9058w92y',
      type: 'door',
      w: 0.9,
      flip: false,
      hinge: true,
      along: 0.6,
    },
    {
      id: 'dmu42c7rvrhps',
      edge: 'e-r11-r12',
      to: 'r12',
      type: 'door',
      w: 0.9,
      flip: true,
      hinge: true,
      along: 0.8,
    },
  ],
  r13: [
    {
      id: 'dmu41n3gsjgzq',
      edge: 'e-EXTERIOR-r13',
      to: 'EXTERIOR',
      type: 'door',
      w: 0.9,
      flip: false,
      hinge: false,
      at: [0, 2.5],
    },
    {
      id: 'dmu41y3dzm6jg',
      edge: 'e-r13-r14',
      to: 'r14',
      type: 'door',
      w: 0.9,
      flip: true,
      hinge: true,
      along: 0.8,
    },
  ],
  r15: [
    {
      id: 'dmu41y1pit73w',
      edge: 'e-r15-r8',
      to: 'r8',
      type: 'door',
      w: 0.9,
      flip: false,
      hinge: true,
      along: 0.8,
    },
  ],
  r16: [
    {
      id: 'dmu41ked5cml0',
      edge: 'e-EXTERIOR-r16',
      to: 'EXTERIOR',
      type: 'street2',
      w: 2,
      flip: true,
      hinge: false,
      at: [1.294091, 9.577081],
    },
    {
      id: 'dmu41uupye9yl',
      edge: 'e-r16-r7',
      to: 'r7',
      type: 'sliding',
      w: 2.5,
      flip: false,
      hinge: false,
      along: 0.507972,
    },
  ],
  nmu3xhurkamdb: [
    {
      id: 'dmu41rcx3prtn',
      edge: 'e-nmu3xhurkamdb-nmu3y9058w92y',
      to: 'nmu3y9058w92y',
      type: 'door',
      w: 0.9,
      flip: false,
      hinge: false,
      along: 0.75,
    },
  ],
  nmu3y9058w92y: [
    {
      id: 'dmu42micq75ps',
      edge: 'e-nmu3y9058w92y-r16',
      to: 'r16',
      type: 'opening',
      w: 1.2,
      flip: false,
      hinge: false,
      along: 0.5,
    },
  ],
}

/** The edges the plan's doors draw, as a project would hold them. */
export const FIXTURE_EDGES: {
  id: string
  a: string
  b: string
  kind: 'door' | 'open' | 'main-door'
  storey: number
}[] = [
  {
    id: 'e-r0-r16',
    a: 'r0',
    b: 'r16',
    kind: 'open',
    storey: 0,
  },
  {
    id: 'e-EXTERIOR-r0',
    a: 'r0',
    b: 'EXTERIOR',
    kind: 'main-door',
    storey: 0,
  },
  {
    id: 'e-r0-r6',
    a: 'r0',
    b: 'r6',
    kind: 'open',
    storey: 0,
  },
  {
    id: 'e-r1-r16',
    a: 'r1',
    b: 'r16',
    kind: 'open',
    storey: 0,
  },
  {
    id: 'e-r2-r3',
    a: 'r2',
    b: 'r3',
    kind: 'open',
    storey: 0,
  },
  {
    id: 'e-EXTERIOR-r2',
    a: 'r2',
    b: 'EXTERIOR',
    kind: 'door',
    storey: 0,
  },
  {
    id: 'e-r2-r7',
    a: 'r2',
    b: 'r7',
    kind: 'door',
    storey: 0,
  },
  {
    id: 'e-r16-r5',
    a: 'r5',
    b: 'r16',
    kind: 'open',
    storey: 0,
  },
  {
    id: 'e-nmu3y9058w92y-r8',
    a: 'r8',
    b: 'nmu3y9058w92y',
    kind: 'door',
    storey: 0,
  },
  {
    id: 'e-EXTERIOR-r8',
    a: 'r8',
    b: 'EXTERIOR',
    kind: 'door',
    storey: 0,
  },
  {
    id: 'e-r10-r16',
    a: 'r10',
    b: 'r16',
    kind: 'door',
    storey: 0,
  },
  {
    id: 'e-nmu3y9058w92y-r11',
    a: 'r11',
    b: 'nmu3y9058w92y',
    kind: 'door',
    storey: 0,
  },
  {
    id: 'e-r11-r12',
    a: 'r11',
    b: 'r12',
    kind: 'door',
    storey: 0,
  },
  {
    id: 'e-EXTERIOR-r13',
    a: 'r13',
    b: 'EXTERIOR',
    kind: 'door',
    storey: 0,
  },
  {
    id: 'e-r13-r14',
    a: 'r13',
    b: 'r14',
    kind: 'door',
    storey: 0,
  },
  {
    id: 'e-r15-r8',
    a: 'r15',
    b: 'r8',
    kind: 'door',
    storey: 0,
  },
  {
    id: 'e-EXTERIOR-r16',
    a: 'r16',
    b: 'EXTERIOR',
    kind: 'door',
    storey: 0,
  },
  {
    id: 'e-r16-r7',
    a: 'r16',
    b: 'r7',
    kind: 'door',
    storey: 0,
  },
  {
    id: 'e-nmu3xhurkamdb-nmu3y9058w92y',
    a: 'nmu3xhurkamdb',
    b: 'nmu3y9058w92y',
    kind: 'door',
    storey: 0,
  },
  {
    id: 'e-nmu3y9058w92y-r16',
    a: 'nmu3y9058w92y',
    b: 'r16',
    kind: 'open',
    storey: 0,
  },
]

/** The plan, ready to work on: the rooms with their defaults filled, their doors, and repaired. */
export function fixtureSheet(settings: Partial<Settings> = {}): Sheet {
  const sheet = sheetOf([], settings)
  const rooms = EMBEDDED_ROOMS.map(
    (r): Room =>
      JSON.parse(
        JSON.stringify({
          angle: 0,
          pieces: null,
          ...r,
          ...(DOORS[r.id] ? { doors: DOORS[r.id] } : {}),
        }),
      ) as Room,
  )
  sheet.rooms = repair(rooms, sheet.settings)
  return sheet
}
