import { expect, it } from 'vitest'
import * as sheet from './index'

/** The surface T2 to T5 and the layout agent drive: every name the sheet offers, and no other. */
const surface = [
  // the plot
  'BUILD',
  'BUILDABLE_AREA',
  'MAX_STOREYS',
  'NORTH',
  'PLOT',
  'PLOT_BOX',
  'RATIO',
  'RATIO_ALLOWED',
  'SIDES',
  'SIDE_BUDGET',
  'SIDE_NAME',
  'STOREY_MARK',
  'STOREY_NAME',
  'STREET_BUDGET',
  'boxCorners',
  // the model
  'DEFAULTS',
  'RULE_HINT',
  'SETTINGS_V',
  'acrossStoreys',
  'allPlaced',
  'cloneRoom',
  'cloneSheet',
  'doorsOf',
  'ghostsOf',
  'heightCap',
  'heightOf',
  'isCourt',
  'isGhost',
  'isOpen',
  'isStair',
  'kin',
  'migrate',
  'piecesOf',
  'placedRooms',
  'rank',
  'ruleOf',
  'sheetOf',
  'snapRooms',
  'stH',
  'storeyCountOf',
  'storeyNameOf',
  'storeyOf',
  'tallRoom',
  'zTop',
  // the geometry
  'areaOf',
  'bboxOf',
  'canonicalise',
  'centreOfFootprint',
  'chainWalls',
  'cutBy',
  'cutShapeToSetback',
  'diffConvex',
  'facing',
  'fmt',
  'intersectConvex',
  'loopsOf',
  'normalise',
  'outlineFrom',
  'outlineOf',
  'overlapCells',
  'partsOf',
  'pullWallShape',
  'r2',
  'r6',
  'setAngle',
  'sideOf',
  'simplifyLoop',
  'tidy',
  'toLocal',
  'toWorld',
  'triangulate',
  'weld',
  'worldCorners',
  'worldPieces',
  'worldWalls',
  // snapping
  'alignWall',
  'closeGaps',
  'gridRest',
  'nearWalls',
  'snapAngle',
  'snapHeight',
  'snapMove',
  'snapPoint',
  'wallCandidates',
  // landing
  'allowedBox',
  'giveWay',
  'hold',
  'outsideBuildable',
  'overlapsOf',
  'partingMove',
  'pushFrom',
  'resolve',
  'settle',
  'yieldTo',
  // enclosed spaces
  'bestNeighbour',
  'courtWhy',
  'givePieces',
  'holdsSquare',
  'pocketsOf',
  'roomFromPocket',
  // doors
  'doorAcross',
  'doorAt',
  'doorBlocked',
  'doorPlace',
  'doorWidth',
  'openWallOn',
  'slideDoorAlong',
  'walkTest',
  // labels
  'initialsOf',
  'labelPlan',
  'obstaclesOf',
  'spanThrough',
  // the report
  'boundaryWalls',
  'report',
  'sideOver',
  'sideUsed',
  // the program and the sample
  'DOOR',
  'KINDS',
  'KIND_INFO',
  'PROGRAM',
  'PROGRAM_TAG',
  'freshRooms',
  'hasHinge',
  'hasSwing',
  'isStreetDoor',
  'repair',
  'sampleSheet',
  'sizeFor',
  // the actions
  'HISTORY_CAP',
  'addDoor',
  'addRoom',
  'addStorey',
  'carveBelow',
  'clearHeight',
  'combine',
  'copyTo',
  'cutToSetback',
  'draw',
  'drawnPoint',
  'dropTopStorey',
  'flipDoor',
  'givePocket',
  'group',
  'hingeDoor',
  'lock',
  'makeCorridor',
  'makeCourt',
  'mirror',
  'move',
  'moveCorner',
  'moveDoor',
  'newHistory',
  'openWall',
  'place',
  'pullWall',
  'pushOthers',
  'reattachDoor',
  'redo',
  'remember',
  'removeDoor',
  'removeRoom',
  'reorder',
  'reshape',
  'resize',
  'restOnGrid',
  'restore',
  'sendBack',
  'sendBackRoom',
  'setArea',
  'setDoorWidth',
  'setHeight',
  'setSetting',
  'setSize',
  'setStorey',
  'slideDoor',
  'turn',
  'undo',
  'ungroup',
  'unlock',
]

it('offers every name the screens and the agent drive, and no other', () => {
  const given = Object.keys(sheet).sort()
  expect(given).toEqual([...surface].sort())
  for (const name of surface) expect(sheet[name as keyof typeof sheet]).toBeDefined()
})

it('opens on the sample sheet and reads it', () => {
  const opened = sheet.sampleSheet()
  expect(sheet.report(opened, 0).walk!.reached).toBe(17)
})
