import { expect, it } from 'vitest'
import * as sheet from './index'

/** The surface T2 to T5 and the layout agent drive: every name the sheet offers, and no other. */
const surface = [
  // the plot
  'MAX_STOREYS',
  'DEFAULT_PLOT',
  'FRESH_PLOT',
  'RATIO',
  'SIDES',
  'STOREY_MARK',
  'STOREY_NAME',
  'boxCorners',
  // the model
  'DEFAULTS',
  'RULE_HINT',
  'SETTINGS_V',
  'acrossStoreys',
  'allPlaced',
  'centreOf',
  'cloneRoom',
  'cloneSheet',
  'doorsOf',
  'ghostsOf',
  'heightCap',
  'heightOf',
  'isCourt',
  'isGhost',
  'isOpen',
  'isStair',
  'kin',
  'migrate',
  'piecesOf',
  'placedRooms',
  'plotFrom',
  'rank',
  'ruleOf',
  'sheetOf',
  'snapRooms',
  'square',
  'stH',
  'storeyCountOf',
  'storeyNameOf',
  'storeyOf',
  'tallRoom',
  'zBase',
  'zTop',
  // the mass
  'BLIND_BREACH',
  'MASS_START',
  'MASS_VIEWS',
  'blindWall',
  'breaches',
  'heightFromDrag',
  'lookFrom',
  'massPivot',
  'massProjection',
  'orderPrisms',
  'prismsOf',
  'recentred',
  'seenWalls',
  'turnedBy',
  'worldLoop',
  'zoomedBy',
  // the geometry
  'areaOf',
  'bboxOf',
  'canonicalise',
  'insideConvex',
  'centreOfFootprint',
  'chainWalls',
  'cutBy',
  'cutShapeToSetback',
  'diffConvex',
  'facing',
  'fmt',
  'intersectConvex',
  'loopsOf',
  'normalise',
  'norm',
  'outlineFrom',
  'outlineOf',
  'overlapRect',
  'overlapCells',
  'partsOf',
  'polyArea',
  'pullWallShape',
  'r2',
  'r6',
  'setAngle',
  'rotateGroup',
  'setFrame',
  'simplePoly',
  'snapTo',
  'sideOf',
  'simplifyLoop',
  'tidy',
  'toLocal',
  'toWorld',
  'triangulate',
  'weld',
  'worldCorners',
  'unionBox',
  'worldPieces',
  'worldWalls',
  // snapping
  'alignWall',
  'closeGaps',
  'gridRest',
  'nearWalls',
  'snapAngle',
  'snapHeight',
  'snapMove',
  'snapPoint',
  'wallCandidates',
  // landing
  'allowedBox',
  'giveWay',
  'hold',
  'outsideBuildable',
  'overlapsOf',
  'partingMove',
  'pushFrom',
  'resolve',
  'settle',
  'yieldTo',
  // enclosed spaces
  'bestNeighbour',
  'courtWhy',
  'givePieces',
  'holdsSquare',
  'pocketsOf',
  'roomFromPocket',
  // doors
  'doorAcross',
  'doorAt',
  'doorBlocked',
  'doorPlace',
  'doorWidth',
  'openWallOn',
  'slideDoorAlong',
  'walkTest',
  // the Openings step
  'doorDrawing',
  'doorNear',
  'doorRead',
  'lostDoors',
  'newDoors',
  // labels
  'initialsOf',
  'labelPlan',
  'obstaclesOf',
  'spanThrough',
  // the report
  'boundaryWalls',
  'report',
  'sideOver',
  'sideUsed',
  // the program and the sample
  'DOOR',
  'KINDS',
  'KIND_INFO',
  'PROGRAM',
  'PROGRAM_TAG',
  'freshRooms',
  'hasHinge',
  'hasSwing',
  'isStreetDoor',
  'repair',
  'sampleSheet',
  'sizeFor',
  // the actions
  'HISTORY_CAP',
  'addDoor',
  'addRoom',
  'addStorey',
  'carveBelow',
  'clearColor',
  'clearHeight',
  'clearLabel',
  'combine',
  'copyTo',
  'cutToSetback',
  'draw',
  'drawnPoint',
  'dropTopStorey',
  'flipDoor',
  'givePocket',
  'group',
  'hingeDoor',
  'lock',
  'makeCorridor',
  'makeCourt',
  'mirror',
  'move',
  'moveCorner',
  'moveDoor',
  'newHistory',
  'openWall',
  'place',
  'pullWall',
  'pushOthers',
  'reattachDoor',
  'redo',
  'remember',
  'removeDoor',
  'removeRoom',
  'reorder',
  'reshape',
  'resize',
  'restOnGrid',
  'restore',
  'sendBack',
  'sendBackRoom',
  'setArea',
  'setColor',
  'setDoorWidth',
  'setHeight',
  'setLabel',
  'setSetting',
  'setSize',
  'setStorey',
  'slideDoor',
  'turn',
  'undo',
  'ungroup',
  'unlock',
  // the assistant's tools, its memory and its prompt
  'layoutTools',
  'newMemory',
  'promptFor',
  'readMemory',
  'sheetRead',
  'withFeedback',
  'withNote',
  'withPlan',
]

it('offers every name the screens and the agent drive, and no other', () => {
  const given = Object.keys(sheet).sort()
  expect(given).toEqual([...surface].sort())
  for (const name of surface) expect(sheet[name as keyof typeof sheet]).toBeDefined()
})

it('opens on the sample sheet and reads it', () => {
  const opened = sheet.sampleSheet()
  expect(sheet.report(opened, 0).walk!.reached).toBe(17)
})
