import type { LegalFloor, RoomType } from './types'

const sizes = 'Kuwait Municipality, minimum room sizes'
const minimumRoom: LegalFloor = { area: 10, width: 3, source: sizes }
const minimumKitchen: LegalFloor = { area: 7.5, width: 2, source: sizes }
const minimumBathroom: LegalFloor = { area: 4, width: 1.75, source: sizes }
const minimumWc: LegalFloor = { area: 1.5, width: 1.2, source: sizes }

/** Transcribed row for row from rulebook/room-types.md, which stays the source a person reads. */
export const roomTypes: readonly RoomType[] = [
  {
    id: 'entry-foyer',
    label: 'Entry / Foyer',
    arabic: 'مدخل',
    typical: 8,
    range: { min: 6, max: 12 },
    proportion: { min: 1, max: 1.5 },
    category: 'shared',
    tier: 'public',
    defaultStorey: 'ground',
    flags: { circulation: true },
    basis: 'judgement',
  },
  {
    id: 'diwaniya',
    label: 'Diwaniya',
    arabic: 'ديوانية',
    legalFloor: minimumRoom,
    typical: 'by plot band',
    range: 'by plot band',
    proportion: { min: 1.2, max: 2 },
    category: 'reception',
    tier: 'public',
    defaultStorey: 'ground',
    companion: 'diwaniya-wc',
    flags: {},
    basis: 'judgement; about 3 m² per seated guest',
  },
  {
    id: 'diwaniya-wc',
    label: 'Diwaniya WC',
    arabic: 'حمام الديوانية',
    legalFloor: minimumBathroom,
    typical: 5,
    range: { min: 4, max: 6 },
    proportion: { min: 1, max: 1.6 },
    category: 'service',
    tier: 'exempt',
    defaultStorey: 'ground',
    flags: { auxiliary: true },
    basis: 'legal',
  },
  {
    id: 'formal-living',
    label: 'Formal Living',
    arabic: 'صالة رسمية',
    legalFloor: minimumRoom,
    typical: 'by plot band',
    range: 'by plot band',
    proportion: { min: 1, max: 1.6 },
    category: 'shared',
    tier: 'public',
    defaultStorey: 'ground',
    flags: {},
    basis: 'judgement',
  },
  {
    id: 'family-living',
    label: 'Family Living',
    arabic: 'صالة المعيشة',
    legalFloor: minimumRoom,
    typical: 'by plot band',
    range: 'by plot band',
    proportion: { min: 1, max: 1.6 },
    category: 'shared',
    tier: 'private',
    defaultStorey: 'any',
    flags: {},
    basis: 'judgement',
  },
  {
    id: 'womens-reception',
    label: "Women's Reception",
    arabic: 'مجلس نساء',
    legalFloor: minimumRoom,
    typical: 30,
    range: { min: 24, max: 40 },
    proportion: { min: 1, max: 1.6 },
    category: 'shared',
    tier: 'public',
    defaultStorey: 'ground',
    flags: { optional: true },
    basis: 'judgement',
  },
  {
    id: 'dining-room',
    label: 'Dining Room',
    arabic: 'غرفة الطعام',
    legalFloor: minimumRoom,
    typical: 24,
    range: { min: 18, max: 32 },
    proportion: { min: 1.2, max: 1.8 },
    category: 'shared',
    tier: 'semi-public',
    defaultStorey: 'ground',
    flags: {},
    basis: 'judgement; 10 to 12 seats',
  },
  {
    id: 'kitchen',
    label: 'Kitchen',
    arabic: 'مطبخ',
    legalFloor: minimumKitchen,
    typical: 20,
    range: { min: 14, max: 28 },
    proportion: { min: 1, max: 1.8 },
    category: 'shared',
    tier: 'private',
    defaultStorey: 'ground',
    flags: {},
    basis: 'legal floor; judgement above',
  },
  {
    id: 'prep-kitchen',
    label: 'Prep Kitchen',
    arabic: 'مطبخ تحضيري',
    legalFloor: minimumKitchen,
    typical: 10,
    range: { min: 8, max: 14 },
    proportion: { min: 1, max: 1.6 },
    category: 'service',
    tier: 'exempt',
    defaultStorey: 'ground',
    flags: {},
    basis: 'judgement',
  },
  {
    id: 'master-bedroom',
    label: 'Master Bedroom',
    arabic: 'غرفة النوم الرئيسية',
    legalFloor: minimumRoom,
    typical: 28,
    range: { min: 22, max: 36 },
    proportion: { min: 1, max: 1.5 },
    category: 'private',
    tier: 'private',
    defaultStorey: 'upper',
    companion: 'ensuite-bathroom',
    flags: {},
    basis: 'judgement',
  },
  {
    id: 'bedroom',
    label: 'Bedroom',
    arabic: 'غرفة نوم',
    legalFloor: minimumRoom,
    typical: 18,
    range: { min: 14, max: 22 },
    proportion: { min: 1, max: 1.5 },
    category: 'private',
    tier: 'private',
    defaultStorey: 'upper',
    companion: 'ensuite-bathroom',
    flags: {},
    basis: 'judgement',
  },
  {
    id: 'ensuite-bathroom',
    label: 'Ensuite Bathroom',
    arabic: 'حمام ملحق',
    legalFloor: minimumBathroom,
    typical: 6,
    range: { min: 5, max: 8 },
    proportion: { min: 1, max: 1.8 },
    category: 'private',
    tier: 'exempt',
    defaultStorey: 'upper',
    flags: { auxiliary: true },
    basis: 'legal',
  },
  {
    id: 'bathroom',
    label: 'Bathroom',
    arabic: 'حمام',
    legalFloor: minimumBathroom,
    typical: 5,
    range: { min: 4, max: 7 },
    proportion: { min: 1, max: 1.8 },
    category: 'private',
    tier: 'exempt',
    defaultStorey: 'upper',
    flags: { auxiliary: true },
    basis: 'legal',
  },
  {
    id: 'guest-wc',
    label: 'Guest WC',
    arabic: 'حمام ضيوف',
    legalFloor: minimumWc,
    typical: 3,
    range: { min: 2.5, max: 4 },
    proportion: { min: 1, max: 1.8 },
    category: 'service',
    tier: 'exempt',
    defaultStorey: 'ground',
    flags: { auxiliary: true },
    basis: 'legal',
  },
  {
    id: 'dressing-room',
    label: 'Dressing Room',
    arabic: 'غرفة ملابس',
    typical: 8,
    range: { min: 6, max: 12 },
    proportion: { min: 1, max: 1.8 },
    category: 'private',
    tier: 'private',
    defaultStorey: 'upper',
    flags: { auxiliary: true },
    basis: 'judgement',
  },
  {
    id: 'office-study',
    label: 'Office / Study',
    arabic: 'مكتب',
    legalFloor: minimumRoom,
    typical: 14,
    range: { min: 12, max: 18 },
    proportion: { min: 1, max: 1.5 },
    category: 'private',
    tier: 'private',
    defaultStorey: 'any',
    flags: {},
    basis: 'judgement',
  },
  {
    id: 'prayer-room',
    label: 'Prayer Room',
    arabic: 'غرفة صلاة',
    legalFloor: { area: 10, width: 3, source: sizes, note: 'as a room' },
    typical: 9,
    range: { min: 6, max: 12 },
    proportion: { min: 1, max: 1.5 },
    category: 'private',
    tier: 'private',
    defaultStorey: 'any',
    flags: {},
    basis: 'judgement; under 10 m² it is an alcove',
  },
  {
    id: 'laundry',
    label: 'Laundry',
    arabic: 'غسيل',
    typical: 8,
    range: { min: 6, max: 10 },
    proportion: { min: 1, max: 1.6 },
    category: 'service',
    tier: 'exempt',
    defaultStorey: 'ground',
    flags: {},
    basis: 'judgement',
  },
  {
    id: 'storage',
    label: 'Storage',
    arabic: 'مخزن',
    typical: 6,
    range: { min: 4, max: 10 },
    proportion: { min: 1, max: 2 },
    category: 'service',
    tier: 'exempt',
    defaultStorey: 'ground',
    flags: {},
    basis: 'judgement',
  },
  {
    id: 'service-entrance',
    label: 'Service Entrance',
    arabic: 'مدخل خدمة',
    typical: 5,
    range: { min: 3, max: 8 },
    proportion: { min: 1, max: 2 },
    category: 'service',
    tier: 'semi-public',
    defaultStorey: 'ground',
    flags: { circulation: true },
    basis: 'judgement',
  },
  {
    id: 'hallway',
    label: 'Hallway',
    arabic: 'ممر',
    legalFloor: { width: 1.2, source: `${sizes} (corridor)`, note: 'clear' },
    typical: { min: 1.5, max: 1.8 },
    range: 'length as needed',
    proportion: 'free',
    category: 'shared',
    tier: 'semi-public',
    defaultStorey: 'any',
    flags: { circulation: true },
    basis: 'legal width',
  },
  {
    id: 'stair',
    label: 'Stair',
    arabic: 'درج',
    legalFloor: {
      width: 1.2,
      source: 'Kuwait Municipality, stairs',
      note: 'clear; riser at most 17 cm; at most 14 risers in one run',
    },
    typical: 15,
    range: { min: 12, max: 20 },
    proportion: { min: 1.6, max: 2.2 },
    category: 'shared',
    tier: 'semi-public',
    defaultStorey: 'all',
    flags: { circulation: true },
    basis: 'legal geometry',
  },
  {
    id: 'lift',
    label: 'Lift',
    arabic: 'مصعد',
    typical: 5,
    range: { min: 4, max: 6 },
    proportion: { min: 1, max: 1 },
    category: 'shared',
    tier: 'semi-public',
    defaultStorey: 'all',
    flags: { circulation: true, notInRatio: true },
    basis: 'judgement',
  },
  {
    id: 'maid-room',
    label: 'Maid Room',
    arabic: 'غرفة خادمة',
    legalFloor: minimumRoom,
    typical: 12,
    range: { min: 10, max: 14 },
    proportion: { min: 1, max: 1.4 },
    category: 'service',
    tier: 'private',
    defaultStorey: 'ground',
    companion: 'maid-bathroom',
    flags: {},
    basis: 'legal floor',
  },
  {
    id: 'maid-bathroom',
    label: 'Maid Bathroom',
    arabic: 'حمام الخادمة',
    legalFloor: minimumBathroom,
    typical: 4.5,
    range: { min: 4, max: 5 },
    proportion: { min: 1, max: 1.6 },
    category: 'service',
    tier: 'exempt',
    defaultStorey: 'ground',
    flags: { auxiliary: true },
    basis: 'legal',
  },
  {
    id: 'driver-room',
    label: 'Driver Room',
    arabic: 'غرفة سائق',
    legalFloor: minimumRoom,
    typical: 12,
    range: { min: 10, max: 14 },
    proportion: { min: 1, max: 1.4 },
    category: 'service',
    tier: 'private',
    defaultStorey: 'ground',
    companion: 'driver-bathroom',
    flags: {},
    basis: 'legal floor',
    note: 'own door, by the garage',
  },
  {
    id: 'driver-bathroom',
    label: 'Driver Bathroom',
    arabic: 'حمام السائق',
    legalFloor: minimumBathroom,
    typical: 4.5,
    range: { min: 4, max: 5 },
    proportion: { min: 1, max: 1.6 },
    category: 'service',
    tier: 'exempt',
    defaultStorey: 'ground',
    flags: { auxiliary: true },
    basis: 'legal',
  },
  {
    id: 'garage',
    label: 'Garage, per car',
    arabic: 'كراج',
    typical: 18,
    range: { min: 16, max: 21 },
    proportion: { min: 1.7, max: 2 },
    category: 'service',
    tier: 'exempt',
    defaultStorey: 'ground',
    flags: {},
    basis: 'judgement; 3 × 6 m bay',
    perCar: true,
  },
  {
    id: 'courtyard',
    label: 'Courtyard',
    arabic: 'حوش / فناء',
    legalFloor: {
      area: 9,
      width: 1.5,
      source: 'Kuwait Municipality, light wells',
      note: 'if it lights rooms',
    },
    typical: 25,
    range: { min: 16, max: 50 },
    proportion: { min: 1, max: 1.6 },
    category: 'open',
    tier: 'exempt',
    defaultStorey: 'ground',
    flags: { notInRatio: true },
    basis: 'legal light well',
  },
  {
    id: 'roof-annex',
    label: 'Roof Annex',
    arabic: 'ملحق السطح',
    legalFloor: {
      source: 'Kuwait Municipality, building ratio',
      note: 'at most 100 m², counted in the ratio',
    },
    typical: 40,
    range: { min: 25, max: 100 },
    proportion: 'free',
    category: 'shared',
    tier: 'private',
    defaultStorey: 'top',
    flags: {},
    basis: 'legal cap',
  },
  {
    id: 'room-other',
    label: 'Room (other)',
    arabic: 'غرفة',
    legalFloor: minimumRoom,
    typical: 12,
    range: { min: 10, max: 20 },
    proportion: { min: 1, max: 1.6 },
    category: 'shared',
    tier: 'exempt',
    defaultStorey: 'any',
    flags: {},
    basis: 'legal floor',
  },
]
